clc;clear all;close all;

Ra_values = [1e8, 1e9, 1e10, 1e11, 1e12];
num_Ra = length(Ra_values);

results = struct();
num_energy_files = 9;

%% E^{m,n}(t)/E_{total}
for i = 1:num_Ra
    Ra_str = sprintf('1e%d', log10(Ra_values(i)));
    
    results(i).summary = load(fullfile(Ra_str, 'Fourier_result_summary.dat'));
    
    energy_data_y = cell(1, num_energy_files);
    
    for j = 1:num_energy_files
        energy_filename = fullfile(Ra_str, sprintf('energyPercentage_%d.dat', j));
        temp_data = load(energy_filename);
        if j == 1
            results(i).time = temp_data(:,1);
        end
        energy_data_y{j} = temp_data(:,2);
    end
    
    results(i).energy_percentages = energy_data_y;
    
    is_legend_shown = 0; 
    line_colors = {'color1','color9','color8','color6','color7','color5','color3','color4','color2'};

    
    plot_matlab('x', results(i).time, 'y', results(i).energy_percentages, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.2, ...
            'LineColor', line_colors, ...
            'YLim', [0, 80], ...
            'XLim', [0, size(results(i).time, 1)], ... 
            'XLabel', '\it{t}', ...
            'YLabel', '\it{E^{m,n}} \rm{(}\it{t}\rm{)}\it{/E_{total}} \rm{(}\it{t}\rm{)} (%)', ...
            'ShowLegend', is_legend_shown, ...
            'OutputFilename', sprintf('energyPercentage_%s.png', Ra_str), ...
            'Resolution', 600);
end

fprintf('Done.\n');

%% E_Ra
result_4 = zeros(size(results(1).summary, 1), num_Ra);
result_5 = zeros(size(results(1).summary, 1), num_Ra);
result_6 = zeros(size(results(1).summary, 1), num_Ra);
result_7 = zeros(size(results(1).summary, 1), num_Ra);

for i = 1:num_Ra
    result_4(:, i) = results(i).summary(:, 4);
    result_5(:, i) = results(i).summary(:, 5);
    result_6(:, i) = results(i).summary(:, 6);
    result_7(:, i) = results(i).summary(:, 7);
end

result_4_cell = num2cell(result_4, 2);
result_5_cell = num2cell(result_5, 2);
result_6_cell = num2cell(result_6, 2);
result_7_cell = num2cell(result_7, 2);

plot_indices = [1, 2, 4, 5];
marker_styles = {'o', '^', 'd', 's'};
marker_colors = {'color1', 'color4', 'color3', 'color2'};
common_plot_options = {'CanvasRatio', [10, 7], ...
                       'XLim', [5e7, 5e12], ...
                       'XTicks', [1e8, 1e10, 1e12], ...
                       'LineColor', marker_colors, ...
                       'LineStyle', 'none', ...
                       'XLabel', '\it{Ra}', ...
                       'Marker', marker_styles, ...
                       'MarkerSize', 10, ...
                       'MarkerInterval', 1, ...
                       'LogScale', 'x', ...
                       'Resolution', 600};

% energyPercentageAvg4.png
plot_matlab('x', Ra_values, 'y', result_4_cell(plot_indices), ...
            common_plot_options{:}, ...
            'YLim', [0, 60], ...
            'YLabel', '\it{<E^{m,n}} \rm{(}\it{t}\rm{)}\it{/E_{total}} \rm{(}\it{t}\rm{)}\it{>}', ...
            'ShowLegend', 1, ...
            'OutputFilename', 'energyPercentageAvg4.png');

% energyPercentageAvg_divide4.png
plot_matlab('x', Ra_values, 'y', result_5_cell(plot_indices), ...
            common_plot_options{:}, ...
            'YLim', [0, 60], ...
            'YLabel', '\it{<E^{m,n}} \rm{(}\it{t}\rm{)}> \it{/<E_{total}} \rm{(}\it{t}\rm{)}\it{>}', ...
            'ShowLegend', 0, ...
            'OutputFilename', 'energyPercentageAvg_divide4.png');

% S4.png
plot_matlab('x', Ra_values, 'y', result_6_cell(plot_indices), ...
            common_plot_options{:}, ...
            'YLabel', '<E^{m,n}>/E^{m,n}_{rms}', ...
            'ShowLegend', 0, ...
            'OutputFilename', 'S4.png');

% rms4.png
plot_matlab('x', Ra_values, 'y', result_7_cell(plot_indices), ...
            common_plot_options{:}, ...
            'YLim', [1e-3, 1], ...
            'YLabel', 'E^{m,n}_{rms}/<E_{total}>', ...
            'LogScale', 'xy', ... 
            'ShowLegend', 0, ...
            'OutputFilename', 'rms4.png');
