clear; close all; clc;

% --- Configuration ---
Ra_vals     = [1e8,  1e9,   1e10,   1e11,   1e12];
result=load('tke_ra.dat');
result=num2cell(result,2);

% --- Plotting ---
disp('Plotting results...');
plot_matlab('x', Ra_vals, 'y', result{1}, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.5, ...
            'LineStyle',  '-', 'LineColor','color1',...
            'Marker', 'o', ...
            'MarkerInterval', 1, ...
            'MarkerSize', 8, ...
            'MarkerFaceColor', 'w', ...
            'XLabel', '\it{Ra}', ...
            'YLabel', '\it{Production}', 'YLim', [1e-4 2e-3], ...
            'LogScale', 'xy', ...
            'OutputFilename', 'p_ra.png', ...
            'Resolution', 600);
plot_matlab('x', Ra_vals, 'y', result{2}, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.5, ...
            'LineStyle',  '-', 'LineColor','color2',...
            'Marker', 's', ...
            'MarkerInterval',1,...
            'MarkerSize', 8, ...
            'MarkerFaceColor', 'w', ...
            'XLabel', '\it{Ra}', ...
            'YLabel', '\it{Dissipation}', ...
            'LogScale','xy','YLim',[1e-4 2e-3],...
            'OutputFilename', 'd_ra.png', ...
            'Resolution', 600);
%%
%nonUniform Weight
function [U_dxWeighted,U_dyWeighted,U_areaWeighted]=nonUniformAverage(U,xGrid,yGrid)
[nx, ny] = size(U);
dx = zeros(1,nx);
dy = zeros(1,ny);

dx(1) = (xGrid(2) -0)/2; 
for i = 2:nx
    dx(i) = (xGrid(i+1) - xGrid(i-1))/2;
end

dy(1) = (yGrid(2) - 0)/2; 
for j = 2:ny
    dy(j) = (yGrid(j+1) - yGrid(j-1))/2; 
end

U_dxWeighted = zeros(nx,ny);
U_dyWeighted = zeros(nx,ny);
U_areaWeighted = zeros(nx,ny);

for j = 1:ny
    for i = 1:nx
        U_dxWeighted(i,j) = U(i,j) .* dx(i);      
        U_dyWeighted(i,j) = U(i,j) .* dy(j);      
        U_areaWeighted(i,j) = U(i,j) .* dx(i) .* dy(j);
    end
end
end