close all
clc
clear

load("Rg_Ra_Results.mat");

figHeight = 540;           
ratio = [10, 7];           
figWidth = figHeight * (ratio(1) / ratio(2));
figUnits = 'points';        
fig = figure('Units', figUnits, ...
             'Position', [100, 100, figWidth, figHeight], ...
             'Color', 'w'); 
h = plot(Ra_list, Rg_list);

set(h, ...
    'LineStyle', 'none', ...        
    'Color', 'r', ...            
    'Marker', 'o', ...              
    'MarkerSize', 10, ...           
    'MarkerEdgeColor', 'r', ...  
    'MarkerFaceColor', 'r', ...  
    'LineWidth', 2);              
ax = gca;

xlim([5e7, 2e12]);        
ylim([0, 0.2]);             
set(ax, 'XTick', [1e8, 1e9, 1e10, 1e11, 1e12]); 
set(ax, 'XScale', 'log');

xlabel('\it{Ra}', 'Interpreter', 'tex', 'FontSize', 25);     
ylabel('\it{R_{g} /H}', 'Interpreter', 'tex', 'FontSize', 25); 

set(ax, ...
    'FontName', 'Times', ...    
    'FontSize', 25, ...             
    'LineWidth', 2, ...           
    'TickDir', 'none', ...          
    'Box', 'on', ...              
    'Layer', 'top');               

outputFilename = 'Rg_Ra.png';
resolution = 600;
print(fig, outputFilename, '-dpng', ['-r', num2str(resolution)]);