clear; close all; clc;

%% 1. 定义需要遍历的瑞利数 (Ra) 和对应的统计平稳起始时间
Re_list = [1e8, 1e9, 1e10, 1e11, 1e12];
num_cases = length(Re_list);

%% 2. 定义颜色方案

% "统计平稳" 部分的颜色，按Ra数从低到高排列
main_colors = {'color8', 'color7', 'color4', 'color2', 'color1'}; % 从深蓝 -> 深红

%% 3. 准备用于存储所有数据分段的容器 (Cell Arrays)
% 每个工况将被拆分为两部分，所以总容量是 num_cases * 2
total_segments = num_cases * 2;
y_instNu_vol = cell(1, total_segments);
y_instNu_k = cell(1, total_segments);
y_instNu_t = cell(1, total_segments);
y_meanNu_vol = cell(1, total_segments);
y_meanNu_k = cell(1, total_segments);
y_meanNu_t = cell(1, total_segments);
t_full= cell(1, total_segments);
plot_colors = {'color8', 'color7', 'color4', 'color2', 'color1'};
plot_legends = cell(1, total_segments);

%% 4. 循环读取数据、拆分并存储
fprintf('开始读取和处理数据...\n');
for i = 1:num_cases
    Re = Re_list(i);
    % 使用 '%1.0e' 格式正确地将数字转换为 '1e8' 这样的字符串
    Re_str = num2str(log10(Re), '1e%d'); 
    
    fprintf('  正在处理工况: Ra = %s\n', Re_str);
    
    % 构建文件路径
    inputDir1 = fullfile(Re_str, 'timeseries_Nu.plt');
    inputDir2 = fullfile(Re_str, 'timeseries_Nu_mean.plt');
    
    if ~exist(inputDir1, 'file') || ~exist(inputDir2, 'file')
        warning('未找到工况 %s 的数据文件，将跳过。', Re_str);
        continue;
    end
    
    % 读取数据
    [inst, ~] = read_tecplot_plt(inputDir1);
    [mean, ~] = read_tecplot_plt(inputDir2);
    
    t_full{i} = mean{1};
    y_instNu_vol{i} = inst{2};
    y_instNu_k{i} = inst{3};
    y_instNu_t{i} = inst{4};
    y_meanNu_vol{i} = mean{2};
    y_meanNu_k{i} = mean{3};
    y_meanNu_t{i} = mean{4};
    
 
end
fprintf('所有数据处理完毕。\n\n');

%% 5. 统一绘图
fprintf('正在生成组合图...\n');

% --- 图 1: 瞬时 Nu 对比 ---
plot_matlab('x', t_full, 'y', y_instNu_vol, ...
            'LineColor', plot_colors, ...
            'Legend', plot_legends, ...
            'ShowLegend', 0, ...
            'CanvasRatio', [10, 7], 'Height', 450, 'Units', 'points', ...
            'LineStyle', '-', 'LineWidth', 1, 'YLim',[1e1,1e3],...
            'XLabel', '\it{t}', 'YLabel', '\it{Nu_{vol}}\rm{(}\it{t}\rm{)}', ...
            'LogScale', 'y', 'Marker', 'none', ...
            'OutputFilename', 'instNu_vol', 'Resolution', 600);

% --- 图 3: 平均 Nu 对比 ---
plot_matlab('x', t_full, 'y', y_meanNu_vol, ...
            'LineColor', plot_colors, ...
            'Legend', plot_legends, ...
            'ShowLegend', 0, ...
            'CanvasRatio', [10, 7], 'Height', 450, 'Units', 'points', ...
            'LineStyle', '-', 'LineWidth', 3, 'YLim',[1e1,1e3],...
            'XLabel', '\it{t}', 'YLabel', '\it{<Nu_{vol}}\rm{(}\it{t}\rm{)}\it{>}', ...
            'LogScale', 'y', 'Marker', 'none', ...
            'OutputFilename', 'meanNu_vol', 'Resolution', 600);

% --- 图 1: 瞬时 Nu 对比 ---
plot_matlab('x', t_full, 'y', y_instNu_k, ...
            'LineColor', plot_colors, ...
            'Legend', plot_legends, ...
            'ShowLegend', 0, ...
            'CanvasRatio', [10, 7], 'Height', 450, 'Units', 'points', ...
            'LineStyle', '-', 'LineWidth', 3, 'YLim',[1e1,1e3],...
            'XLabel', '\it{t}', 'YLabel', '\it{Nu_{kinetic}}\rm{(}\it{t}\rm{)}', ...
            'LogScale', 'y', 'Marker', 'none', ...
            'OutputFilename', 'instNu_k', 'Resolution', 600);

% --- 图 3: 平均 Nu 对比 ---
plot_matlab('x', t_full, 'y', y_meanNu_k, ...
            'LineColor', plot_colors, ...
            'Legend', plot_legends, ...
            'ShowLegend', 0, ...
            'CanvasRatio', [10, 7], 'Height', 450, 'Units', 'points', ...
            'LineStyle', '-', 'LineWidth', 3, 'YLim',[1e1,1e3],...
            'XLabel', '\it{t}', 'YLabel', '\it{<Nu_{kinetic}}\rm{(}\it{t}\rm{)}\it{>}', ...
            'LogScale', 'y', 'Marker', 'none', ...
            'OutputFilename', 'meanNu_k', 'Resolution', 600);
% --- 图 1: 瞬时 Nu 对比 ---
plot_matlab('x', t_full, 'y', y_instNu_t, ...
            'LineColor', plot_colors, ...
            'Legend', plot_legends, ...
            'ShowLegend', 0, ...
            'CanvasRatio', [10, 7], 'Height', 450, 'Units', 'points', ...
            'LineStyle', '-', 'LineWidth', 3, 'YLim',[1e1,1e3],...
            'XLabel', '\it{t}', 'YLabel', '\it{Nu_{thermal}}\rm{(}\it{t}\rm{)}', ...
            'LogScale', 'y', 'Marker', 'none', ...
            'OutputFilename', 'instNu_t', 'Resolution', 600);

% --- 图 3: 平均 Nu 对比 ---
plot_matlab('x', t_full, 'y', y_meanNu_t, ...
            'LineColor', plot_colors, ...
            'Legend', plot_legends, ...
            'ShowLegend', 0, ...
            'CanvasRatio', [10, 7], 'Height', 450, 'Units', 'points', ...
            'LineStyle', '-', 'LineWidth', 3, 'YLim',[1e1,1e3],...
            'XLabel', '\it{t}', 'YLabel', '\it{<Nu_{thermal}}\rm{(}\it{t}\rm{)}\it{>}', ...
            'LogScale', 'y', 'Marker', 'none', ...
            'OutputFilename', 'meanNu_t', 'Resolution', 600);

fprintf('所有组合图已生成完毕。\n');