clear; clc; close all;

% ==== 示例 1: 多曲线线性图 (来自您之前的示例) ====
x_data = linspace(-5, 5, 200);
y_data = exp(-x_data.^2 / 2) .* cos(3*x_data);
y_data2 = 1.5*cos(3*x_data);
plot_matlab('x', x_data, 'y', {y_data,y_data2}, ...
            'CanvasRatio', [10, 7], ...
            'XLim', [-5, 5], ...
            'YLim', [-2, 2], ...
            'XTickInterval', 2, ...
            'YTickInterval', 0.5, ...
            'LineColor', {[0.8500, 0.3250, 0.0980],[30/255,144/255,255/255]}, ...
            'LineWidth', 1.5, ...
            'LineStyle', {'-', '-'}, ...
            'Marker', {'o', 's'}, ...
            'MarkerSize', 8, ...
            'MarkerFaceColor', 'w', ...
            'MarkerInterval', 10, ...
            'XLabel', '\it{Time} \rm{(s)}', ...
            'YLabel', '\it{Amplitude}', ...
            'LegendLabels',{'Gauss Modulated','Cosine'},...
            'OutputFilename', 'example1_linear_multi_curve.png', ...
            'Resolution', 600);

% ==== 示例 2: 双对数坐标图 (新功能演示) ====
% 生成适合对数坐标的数据 (例如，幂律关系)
x_log = logspace(-1, 2, 100); % 从 10^-1 到 10^2
y_log = 50 * x_log.^-1.5;     % y = 50 * x^(-1.5)
plot_matlab('x', x_log, 'y', y_log, ...
            'LogScale', 'xy', ... % <-- 使用双对数坐标
            'LineWidth', 2, ...
            'Marker', 'o', ...
            'MarkerInterval',10,...
            'MarkerFaceColor', 'w', ...
            'XLabel', '\it{Frequency} \rm{(Hz)}', ...
            'YLabel', 'PSD', ...
            'OutputFilename', 'example2_loglog_plot.png');

% ==== 示例 3: Y轴对数坐标图 (半对数图) ====
x_semilog = linspace(0, 5, 200);
y_semilog = 100 * exp(-1.5 * x_semilog); % 指数衰减
plot_matlab(x_semilog, y_semilog, ...
            'LogScale', 'y', ... % <-- 仅Y轴为对数
            'LineWidth', 2, ...
            'LineColor', 'r', ...
            'XLabel', '\it{t}', ...
            'YLabel', '\it{Concentration} \rm{(log scale)}', ...
            'YLim', [1, 100], ... % 在对数尺度上设置范围
            'OutputFilename', 'example3_semilogy_plot.png');
            
% ==== 示例 4: 从文件绘图 (假设 u_y.plt 存在) ====
% 假设 'u_y.plt' 是一个简单的ASCII文件，第一列是时间，其他是数据
% 如果文件不存在，可以手动创建一个：
% data_for_file = [linspace(0,10,50)', rand(50,3)+1]; 
% writematrix(data_for_file, 'u_y.plt', 'Delimiter', ' ');

if exist('u_y.plt', 'file')
    plot_matlab('DataSource', 'file', 'Filename', 'u_y.plt', ...
                'XVariable', 2, 'YVariable', 3, ...
                'LineColor', 'r', 'XLabel', '\it{y}', 'YLabel', '\it{u^+}','LogScale', 'x', ...
                'OutputFilename', 'example4_file_plot.png');
else
    disp('跳过文件绘图示例: u_y.plt 不存在。');
end


% ====示例 5： 多文件多曲线 ====
  plot_matlab('Filename', {'timeseries_Nu1e8.plt', 'timeseries_Nu1e9.plt','timeseries_Nu1e10.plt','timeseries_Nu1e11.plt','timeseries_Nu1e12.plt'}, ...
              'XVariable', 't', ...
              'XLim',[-0.1,8000],...
              'LineWidth',1,...
              'YVariable', 'NuETAvg', ...
              'XLabel','\it{t}',...
              'YLabel','\it{Nu_{thermal}}',...
              'ShowLegend', 0, ...
              'LogScale','y',...
              'OutputFilename', 'multi_file_comparison.png');

% ====示例 6 ： 简单计算（+-*/） ====
plot_matlab('Filename', 'u_y.plt', ...
            'XVariable', 'Var1', ... % 使用第一列作为X轴
            'YVariable', '(Var3 + Var3+Var4) ', ... % 使用计算出的平均值作为Y轴
            'XLabel', '\it{t}', ...
            'YLabel', 'Sum', ...
            'LegendLabels', {'Sum'}, ... % 为计算出的曲线提供图例
            'OutputFilename', 'calculation_from_numeric_file.png');