clc; clear all; close all;

result1e8=load('1e8\Fourier_result_summary.dat');
load('1e8\energyPercentage_1.dat')
load('1e8\energyPercentage_2.dat')
load('1e8\energyPercentage_3.dat')
load('1e8\energyPercentage_4.dat')
load('1e8\energyPercentage_5.dat')
load('1e8\energyPercentage_6.dat')
load('1e8\energyPercentage_7.dat')
load('1e8\energyPercentage_8.dat')
load('1e8\energyPercentage_9.dat')

plot_matlab('x', energyPercentage_1(:,1), 'y', {energyPercentage_1(:,2),energyPercentage_2(:,2),energyPercentage_3(:,2),energyPercentage_4(:,2),energyPercentage_5(:,2),energyPercentage_6(:,2),energyPercentage_7(:,2),energyPercentage_8(:,2),energyPercentage_9(:,2)}, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.2, ...
            'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
            'YLim',[0,80],...
            'XLabel', '\it{t} ', ...
            'YLabel', '\it{E^{m,n}} \rm{(}\it{t}\rm{)}\it{/E_{total}} \rm{(}\it{t}\rm{)} (%)', ...
            'ShowLegend',1,...
            'OutputFilename', 'energyPercentage_1e8.png', ...
            'Resolution', 600);

result1e9=load('1e9\Fourier_result_summary.dat');
load('1e9\energyPercentage_1.dat')
load('1e9\energyPercentage_2.dat')
load('1e9\energyPercentage_3.dat')
load('1e9\energyPercentage_4.dat')
load('1e9\energyPercentage_5.dat')
load('1e9\energyPercentage_6.dat')
load('1e9\energyPercentage_7.dat')
load('1e9\energyPercentage_8.dat')
load('1e9\energyPercentage_9.dat')

plot_matlab('x', energyPercentage_1(:,1), 'y', {energyPercentage_1(:,2),energyPercentage_2(:,2),energyPercentage_3(:,2),energyPercentage_4(:,2),energyPercentage_5(:,2),energyPercentage_6(:,2),energyPercentage_7(:,2),energyPercentage_8(:,2),energyPercentage_9(:,2)}, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.2, ...
            'YLim',[0,80],...
            'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
            'XLabel', '\it{t} ', ...
            'YLabel', '\it{E^{m,n}} \rm{(}\it{t}\rm{)} \it{/E_{total}} \rm{(}\it{t}\rm{)} (%)', ...
            'ShowLegend',0,...
            'OutputFilename', 'energyPercentage_1e9.png', ...
            'Resolution', 600);

result1e10=load('1e10\Fourier_result_summary.dat');
load('1e10\energyPercentage_1.dat')
load('1e10\energyPercentage_2.dat')
load('1e10\energyPercentage_3.dat')
load('1e10\energyPercentage_4.dat')
load('1e10\energyPercentage_5.dat')
load('1e10\energyPercentage_6.dat')
load('1e10\energyPercentage_7.dat')
load('1e10\energyPercentage_8.dat')
load('1e10\energyPercentage_9.dat')

plot_matlab('x', energyPercentage_1(:,1), 'y', {energyPercentage_1(:,2),energyPercentage_2(:,2),energyPercentage_3(:,2),energyPercentage_4(:,2),energyPercentage_5(:,2),energyPercentage_6(:,2),energyPercentage_7(:,2),energyPercentage_8(:,2),energyPercentage_9(:,2)}, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.2, ...
            'YLim',[0,80],...
            'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
            'XLabel', '\it{t} ', ...
            'YLabel', '\it{E^{m,n}} \rm{(}\it{t}\rm{)} \it{/E_{total}} \rm{(}\it{t}\rm{)} (%)', ...
            'ShowLegend',0,...
            'OutputFilename', 'energyPercentage_1e10.png', ...
            'Resolution', 600);

result1e11=load('1e11\Fourier_result_summary.dat');
load('1e11\energyPercentage_1.dat')
load('1e11\energyPercentage_2.dat')
load('1e11\energyPercentage_3.dat')
load('1e11\energyPercentage_4.dat')
load('1e11\energyPercentage_5.dat')
load('1e11\energyPercentage_6.dat')
load('1e11\energyPercentage_7.dat')
load('1e11\energyPercentage_8.dat')
load('1e11\energyPercentage_9.dat')

plot_matlab('x', energyPercentage_1(:,1), 'y', {energyPercentage_1(:,2),energyPercentage_2(:,2),energyPercentage_3(:,2),energyPercentage_4(:,2),energyPercentage_5(:,2),energyPercentage_6(:,2),energyPercentage_7(:,2),energyPercentage_8(:,2),energyPercentage_9(:,2)}, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.2, ...
            'XLim',[0,size(energyPercentage_9,1)],...
            'YLim',[0,80],...
            'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
            'XLabel', '\it{t} ', ...
            'YLabel', '\it{E^{m,n}} \rm{(}\it{t}\rm{)} \it{/E_{total}} \rm{(}\it{t}\rm{)} (%)', ...
            'ShowLegend',0,...
            'OutputFilename', 'energyPercentage_1e11.png', ...
            'Resolution', 600);

result1e12=load('1e12\Fourier_result_summary.dat');
load('1e12\energyPercentage_1.dat')
load('1e12\energyPercentage_2.dat')
load('1e12\energyPercentage_3.dat')
load('1e12\energyPercentage_4.dat')
load('1e12\energyPercentage_5.dat')
load('1e12\energyPercentage_6.dat')
load('1e12\energyPercentage_7.dat')
load('1e12\energyPercentage_8.dat')
load('1e12\energyPercentage_9.dat')

plot_matlab('x', energyPercentage_1(:,1), 'y', {energyPercentage_1(:,2),energyPercentage_2(:,2),energyPercentage_3(:,2),energyPercentage_4(:,2),energyPercentage_5(:,2),energyPercentage_6(:,2),energyPercentage_7(:,2),energyPercentage_8(:,2),energyPercentage_9(:,2)}, ...
            'CanvasRatio', [10, 7], ...
            'LineWidth', 1.2, ...
            'XLim',[0,size(energyPercentage_9,1)],...
            'YLim',[0,80],...
            'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
            'XLabel', '\it{t} ', ...
            'YLabel', '\it{E^{m,n}} \rm{(}\it{t}\rm{)} \it{/E_{total}} \rm{(}\it{t}\rm{)} (%)', ...
            'ShowLegend',0,...
            'OutputFilename', 'energyPercentage_1e12.png', ...
            'Resolution', 600);

%%
Ra=[1e8,1e9,1e10,1e11,1e12];
result_4= [result1e8(:,4),result1e9(:,4),result1e10(:,4),result1e11(:,4),result1e12(:,4)];
result_4=num2cell(result_4,2);

% plot_matlab('x', Ra, 'y',result_4, ...
%             'CanvasRatio', [10, 7], ...
%             'XLim',[5e7,5e12],...
%             'XTicks', [1e8, 1e10, 1e12], ...
%             'YLim',[0,60],...
%             'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
%             'LineStyle', 'none', ...
%             'XLabel', '\it{Ra} ', ...
%             'YLabel', '\it{<E^{m,n}} \rm{(}\it{t}\rm{)} \it{/E_{total}} \rm{(}\it{t}\rm{)}\it{>}', ...
%             'Marker', {'o','^','+','<','s','x','>','*','d'}, ...
%             'MarkerSize', 10, ...
%             'MarkerInterval', 1, ...
%             'ShowLegend',0,...
%             'LogScale','x',...
%             'OutputFilename', 'energyPercentageAvg.png', ...
%             'Resolution', 600);

plot_matlab('x', Ra, 'y',result_4([1,2,4,5]), ...
            'CanvasRatio', [10, 7], ...
            'XLim',[5e7,5e12],...
            'XTicks', [1e8, 1e10, 1e12], ...
            'YLim',[0,60],...
            'LineColor',{'color1','color4','color3','color2'},...
            'LineStyle', 'none', ...
            'XLabel', '\it{Ra} ', ...
            'YLabel', '\it{<E^{m,n}} \rm{(}\it{t}\rm{)} \it{/E_{total}} \rm{(}\it{t}\rm{)}\it{>}', ...
            'Marker', {'o','^','d','s'}, ...
            'MarkerSize', 10, ...
            'MarkerInterval', 1, ...
            'ShowLegend',1,...
            'LogScale','x',...
            'OutputFilename', 'energyPercentageAvg4.png', ...
            'Resolution', 600);

result_5= [result1e8(:,5),result1e9(:,5),result1e10(:,5),result1e11(:,5),result1e12(:,5)];
result_5=num2cell(result_5,2);

% plot_matlab('x', Ra, 'y',result_5, ...
%             'CanvasRatio', [10, 7], ...
%             'XLim',[5e7,5e12],...
%             'XTicks', [1e8, 1e10, 1e12], ...
%             'YLim',[0,60],...
%             'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
%             'LineStyle', 'none', ...
%             'XLabel', '\it{Ra} ', ...
%             'YLabel', '\it{<E^{m,n}} \rm{(}\it{t}\rm{)}> \it{/<E_{total}} \rm{(}\it{t}\rm{)}\it{>}', ...
%             'Marker', {'o','^','+','<','s','x','>','*','d'}, ...
%             'MarkerSize',10, ...
%             'MarkerInterval', 1, ...
%             'ShowLegend',0,...
%             'LogScale','x',...
%             'OutputFilename', 'energyPercentageAvg_divide.png', ...
%             'Resolution', 600);

plot_matlab('x', Ra, 'y',result_5([1,2,4,5]), ...
            'CanvasRatio', [10, 7], ...
            'XLim',[5e7,5e12],...
            'XTicks', [1e8, 1e10, 1e12], ...
            'YLim',[0,60],...
            'LineColor',{'color1','color4','color3','color2'},...
            'LineStyle', 'none', ...
            'XLabel', '\it{Ra} ', ...
            'YLabel', '\it{<E^{m,n}} \rm{(}\it{t}\rm{)}> \it{/<E_{total}} \rm{(}\it{t}\rm{)}\it{>}', ...
            'Marker', {'o','^','d','s'}, ...
            'MarkerSize',10, ...
            'MarkerInterval', 1, ...
            'ShowLegend',0,...
            'LogScale','x',...
            'OutputFilename', 'energyPercentageAvg_divide4.png', ...
            'Resolution', 600);

result_6= [result1e8(:,6),result1e9(:,6),result1e10(:,6),result1e11(:,6),result1e12(:,6)];
result_6=num2cell(result_6,2);

% plot_matlab('x', Ra, 'y',result_6, ...
%             'CanvasRatio', [10, 7], ...
%             'XLim',[5e7,5e12],...
%             'XTicks', [1e8, 1e10, 1e12], ...
%             'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
%             'LineStyle', 'none', ...
%             'XLabel', '\it{Ra} ', ...
%             'YLabel', '<E^{m,n}>/E^{m,n}_{rms}', ...
%             'Marker', {'o','^','+','<','s','x','>','*','d'}, ...
%             'MarkerSize', 10, ...
%             'MarkerInterval', 1, ...
%             'ShowLegend',0,...
%             'LogScale','x',...
%             'OutputFilename', 'S.png', ...
%             'Resolution', 600);

plot_matlab('x', Ra, 'y',result_6([1,2,4,5]), ...
            'CanvasRatio', [10, 7], ...
            'XLim',[5e7,5e12],...
            'XTicks', [1e8, 1e10, 1e12], ...
            'LineColor',{'color1','color4','color3','color2'},...
            'LineStyle', 'none', ...
            'XLabel', '\it{Ra} ', ...
            'YLabel', '<E^{m,n}>/E^{m,n}_{rms}', ...
            'Marker', {'o','^','d','s'}, ...
            'MarkerSize', 10, ...
            'MarkerInterval', 1, ...
            'ShowLegend',0,...
            'LogScale','x',...
            'OutputFilename', 'S4.png', ...
            'Resolution', 600);

result_7= [result1e8(:,7),result1e9(:,7),result1e10(:,7),result1e11(:,7),result1e12(:,7)];
result_7=num2cell(result_7,2);

% plot_matlab('x', Ra, 'y',result_7, ...
%             'CanvasRatio', [10, 7], ...
%             'XLim',[5e7,5e12],...
%             'YLim',[1e-3,1],...
%             'XTicks', [1e8, 1e10, 1e12], ...
%             'LineColor',{'color1','color9','color8','color6','color7','color5','color3','color4','color2'},...
%             'LineStyle', 'none', ...
%             'XLabel', '\it{Ra} ', ...
%             'YLabel', 'E^{m,n}_{rms}/<E_{total}>', ...
%             'Marker', {'o','^','+','<','s','x','>','*','d'}, ...
%             'MarkerSize', 10, ...
%             'MarkerInterval', 1, ...
%             'ShowLegend',0,...
%             'LogScale','xy',...
%             'OutputFilename', 'rms.png', ...
%             'Resolution', 600);

plot_matlab('x', Ra, 'y',result_7([1,2,4,5]), ...
            'CanvasRatio', [10, 7], ...
            'XLim',[5e7,5e12],...
            'YLim',[1e-3,1],...
            'XTicks', [1e8, 1e10, 1e12], ...
            'LineColor',{'color1','color4','color3','color2'},...
            'LineStyle', 'none', ...
            'XLabel', '\it{Ra} ', ...
            'YLabel', 'E^{m,n}_{rms}/<E_{total}>', ...
            'Marker', {'o','^','d','s'}, ...
            'MarkerSize', 10, ...
            'MarkerInterval', 1, ...
            'ShowLegend',0,...
            'LogScale','xy',...
            'OutputFilename', 'rms4.png', ...
            'Resolution', 600);